Repository VitDeck/VitDeck, pull requests merged in 2019-05, with the labels that each got.

#7 Feature/#6 ランチャー作成
  VitDeck/Assets/VitDeck/Main/GUI/InfoWindow.cs
  VitDeck/Assets/VitDeck/Main/GUI/InfoWindow.cs.meta
  VitDeck/Assets/VitDeck/Main/GUI/MainMenu.cs
  VitDeck/Assets/VitDeck/Main/GUI/MainMenu.cs.meta
  VitDeck/Assets/VitDeck/Main/Tests/VitDeck.Main.Tests.asmdef
  VitDeck/Assets/VitDeck/Main/Tests/VitDeckTest.cs
  VitDeck/Assets/VitDeck/Main/Tests/VitDeckTest.cs.meta
  VitDeck/Assets/VitDeck/Main/VitDeck.cs
  VitDeck/Assets/VitDeck/Main/VitDeck.cs.meta
  VitDeck/Assets/VitDeck/Utilities/Tests/VersionUtilityTest.cs
  VitDeck/Assets/VitDeck/Utilities/Tests/VersionUtilityTest.cs.meta
  VitDeck/Assets/VitDeck/Utilities/VersionUtility.cs
  VitDeck/Assets/VitDeck/Utilities/VersionUtility.cs.meta
Labels: enhancement

#12 Create temporary scene
  VitDeck/Assets/New Scene.unity
  VitDeck/Assets/New Scene.unity.meta
Labels: enhancement

#14 Change namespace naming
  VitDeck/Assets/VitDeck/Main/Tests/VitDeckTest.cs
  VitDeck/Assets/VitDeck/Utilities/Tests/VersionUtilityTest.cs
  VitDeck/Assets/VitDeck/Utilities/VersionUtility.cs
Labels: enhancement

#15 Feature/#8
  VitDeck/Assets/VitDeck/Images.meta
  VitDeck/Assets/VitDeck/Images/Link_icon.png
  VitDeck/Assets/VitDeck/Images/Link_icon.png.meta
  VitDeck/Assets/VitDeck/Main/GUI/InfoWindow.cs
  VitDeck/Assets/VitDeck/Utilities/AssetUtility.cs
  VitDeck/Assets/VitDeck/Utilities/AssetUtility.cs.meta
  VitDeck/Assets/VitDeck/Utilities/CustomGUILayout.cs
  VitDeck/Assets/VitDeck/Utilities/CustomGUILayout.cs.meta
  VitDeck/Assets/VitDeck/Utilities/Tests/AssetUtilityTest.cs
  VitDeck/Assets/VitDeck/Utilities/Tests/AssetUtilityTest.cs.meta
  VitDeck/Assets/VitDeck/Utilities/Tests/URLUtilityTest.cs
  VitDeck/Assets/VitDeck/Utilities/Tests/URLUtilityTest.cs.meta
  VitDeck/Assets/VitDeck/Utilities/URLUtility.cs
  VitDeck/Assets/VitDeck/Utilities/URLUtility.cs.meta
Labels: enhancement

#22 Feature/#19
  VitDeck/Assets/VitDeck/TemplateLoader/TemplateProperty.cs
  VitDeck/Assets/VitDeck/TemplateLoader/TemplateProperty.cs.meta
  VitDeck/Assets/VitDeck/TemplateLoader/VitDeckDummy.cs
  VitDeck/Assets/VitDeck/TemplateLoader/VitDeckDummy.cs.meta
  VitDeck/Assets/VitDeck/Templates.meta
  VitDeck/Assets/VitDeck/Templates/.gitkeep
  VitDeck/Assets/VitDeck/Templates/Sample_template.meta
  VitDeck/Assets/VitDeck/Templates/Sample_template/LICENSE.txt
  VitDeck/Assets/VitDeck/Templates/Sample_template/LICENSE.txt.meta
  VitDeck/Assets/VitDeck/Templates/Sample_template/Property.asset
  VitDeck/Assets/VitDeck/Templates/Sample_template/Property.asset.meta
  VitDeck/Assets/VitDeck/Templates/Sample_template/SharedAssets.meta
  VitDeck/Assets/VitDeck/Templates/Sample_template/SharedAssets/Shared_asset_A.meta
  VitDeck/Assets/VitDeck/Templates/Sample_template/SharedAssets/Shared_asset_A.prefab
  VitDeck/Assets/VitDeck/Templates/Sample_template/SharedAssets/Shared_asset_A.prefab.meta
  VitDeck/Assets/VitDeck/Templates/Sample_template/SharedAssets/Shared_asset_A/Shared_asset.fbx
  VitDeck/Assets/VitDeck/Templates/Sample_template/SharedAssets/Shared_asset_A/Shared_asset.fbx.meta
  VitDeck/Assets/VitDeck/Templates/Sample_template/SharedAssets/Shared_asset_A/Shared_asset_material.mat
  VitDeck/Assets/VitDeck/Templates/Sample_template/SharedAssets/Shared_asset_A/Shared_asset_material.mat.meta
  VitDeck/Assets/VitDeck/Templates/Sample_template/SharedAssets/Shared_asset_A/Shared_asset_texture.png
  VitDeck/Assets/VitDeck/Templates/Sample_template/SharedAssets/Shared_asset_A/Shared_asset_texture.png.meta
  VitDeck/Assets/VitDeck/Templates/Sample_template/SharedAssets/Support_object.meta
  VitDeck/Assets/VitDeck/Templates/Sample_template/SharedAssets/Support_object/NotEditableComponent.cs
  VitDeck/Assets/VitDeck/Templates/Sample_template/SharedAssets/Support_object/NotEditableComponent.cs.meta
  VitDeck/Assets/VitDeck/Templates/Sample_template/SharedAssets/Support_object/ScaleLimitVisualizer.cs
  VitDeck/Assets/VitDeck/Templates/Sample_template/SharedAssets/Support_object/ScaleLimitVisualizer.cs.meta
  VitDeck/Assets/VitDeck/Templates/Sample_template/SharedAssets/Support_object/Support_objects.prefab
  VitDeck/Assets/VitDeck/Templates/Sample_template/SharedAssets/Support_object/Support_objects.prefab.meta
  VitDeck/Assets/VitDeck/Templates/Sample_template/TemplateAssets.meta
  VitDeck/Assets/VitDeck/Templates/Sample_template/TemplateAssets/{BOOTHID}_{NAME}.meta
  VitDeck/Assets/VitDeck/Templates/Sample_template/TemplateAssets/{BOOTHID}_{NAME}/Materials.meta
  VitDeck/Assets/VitDeck/Templates/Sample_template/TemplateAssets/{BOOTHID}_{NAME}/Materials/Dummy.asset
  VitDeck/Assets/VitDeck/Templates/Sample_template/TemplateAssets/{BOOTHID}_{NAME}/Materials/Dummy.asset.meta
  VitDeck/Assets/VitDeck/Templates/Sample_template/TemplateAssets/{BOOTHID}_{NAME}/Models.meta
  VitDeck/Assets/VitDeck/Templates/Sample_template/TemplateAssets/{BOOTHID}_{NAME}/Models/Sample_object.fbx
  VitDeck/Assets/VitDeck/Templates/Sample_template/TemplateAssets/{BOOTHID}_{NAME}/Models/Sample_object.fbx.meta
  VitDeck/Assets/VitDeck/Templates/Sample_template/TemplateAssets/{BOOTHID}_{NAME}/Scene_{BOOTHID}_{NAME}.unity
  VitDeck/Assets/VitDeck/Templates/Sample_template/TemplateAssets/{BOOTHID}_{NAME}/Scene_{BOOTHID}_{NAME}.unity.meta
  VitDeck/Assets/VitDeck/Templates/Sample_template/TemplateAssets/{BOOTHID}_{NAME}/Shaders.meta
  VitDeck/Assets/VitDeck/Templates/Sample_template/TemplateAssets/{BOOTHID}_{NAME}/Shaders/Dummy.asset
  VitDeck/Assets/VitDeck/Templates/Sample_template/TemplateAssets/{BOOTHID}_{NAME}/Shaders/Dummy.asset.meta
Labels: enhancement

#27 Feature/#10
  VitDeck/Assets/VitDeck/AssetGuardian.meta
  VitDeck/Assets/VitDeck/AssetGuardian/DelayedDeprotector.cs
  VitDeck/Assets/VitDeck/AssetGuardian/DelayedDeprotector.cs.meta
  VitDeck/Assets/VitDeck/AssetGuardian/GUI.meta
  VitDeck/Assets/VitDeck/AssetGuardian/GUI/Notificator.cs
  VitDeck/Assets/VitDeck/AssetGuardian/GUI/Notificator.cs.meta
  VitDeck/Assets/VitDeck/AssetGuardian/GUI/VitDeck.AssetGuardian.GUI.asmdef
  VitDeck/Assets/VitDeck/AssetGuardian/GUI/VitDeck.AssetGuardian.GUI.asmdef.meta
  VitDeck/Assets/VitDeck/AssetGuardian/Guardian.cs
  VitDeck/Assets/VitDeck/AssetGuardian/Guardian.cs.meta
  VitDeck/Assets/VitDeck/AssetGuardian/Handler.cs
  VitDeck/Assets/VitDeck/AssetGuardian/Handler.cs.meta
  VitDeck/Assets/VitDeck/AssetGuardian/ProtectedAssetPostProcessor.cs
  VitDeck/Assets/VitDeck/AssetGuardian/ProtectedAssetPostProcessor.cs.meta
  VitDeck/Assets/VitDeck/AssetGuardian/ProtectionLabel.cs
  VitDeck/Assets/VitDeck/AssetGuardian/ProtectionLabel.cs.meta
  VitDeck/Assets/VitDeck/AssetGuardian/Tests.meta
  VitDeck/Assets/VitDeck/AssetGuardian/Tests/GuardianTest.cs
  VitDeck/Assets/VitDeck/AssetGuardian/Tests/GuardianTest.cs.meta
  VitDeck/Assets/VitDeck/AssetGuardian/Tests/ProtectionLabelTest.cs
  VitDeck/Assets/VitDeck/AssetGuardian/Tests/ProtectionLabelTest.cs.meta
  VitDeck/Assets/VitDeck/AssetGuardian/Tests/TestScriptableObject.cs
  VitDeck/Assets/VitDeck/AssetGuardian/Tests/TestScriptableObject.cs.meta
  VitDeck/Assets/VitDeck/AssetGuardian/Tests/VitDeck.AssetGuardian.Tests.asmdef
  VitDeck/Assets/VitDeck/AssetGuardian/Tests/VitDeck.AssetGuardian.Tests.asmdef.meta
  VitDeck/Assets/VitDeck/AssetGuardian/UnityAssetDuplicationEvent.cs
  VitDeck/Assets/VitDeck/AssetGuardian/UnityAssetDuplicationEvent.cs.meta
  VitDeck/Assets/VitDeck/AssetGuardian/VitDeck.AssetGuardian.asmdef
  VitDeck/Assets/VitDeck/AssetGuardian/VitDeck.AssetGuardian.asmdef.meta
  VitDeck/Assets/VitDeck/Utilities/AssetUtility.cs
  VitDeck/Assets/VitDeck/Utilities/IOUtility.cs
  VitDeck/Assets/VitDeck/Utilities/IOUtility.cs.meta
Labels: Main, enhancement

#41 Feature/#17
  VitDeck/Assets/VitDeck/TemplateLoader/AnimationClipReferenceModifier.cs
  VitDeck/Assets/VitDeck/TemplateLoader/AnimationClipReferenceModifier.cs.meta
  VitDeck/Assets/VitDeck/TemplateLoader/FbxReferenceModifier.cs
  VitDeck/Assets/VitDeck/TemplateLoader/FbxReferenceModifier.cs.meta
  VitDeck/Assets/VitDeck/TemplateLoader/GUI/TemplateLoaderGUI.cs
  VitDeck/Assets/VitDeck/TemplateLoader/GuidReferenceModifier.cs
  VitDeck/Assets/VitDeck/TemplateLoader/GuidReferenceModifier.cs.meta
  VitDeck/Assets/VitDeck/TemplateLoader/IReferenceModifier.cs
  VitDeck/Assets/VitDeck/TemplateLoader/IReferenceModifier.cs.meta
  VitDeck/Assets/VitDeck/TemplateLoader/ReplacementDefinition.cs
  VitDeck/Assets/VitDeck/TemplateLoader/ReplacementDefinition.cs.meta
  VitDeck/Assets/VitDeck/TemplateLoader/TemplateLoader.cs
  VitDeck/Assets/VitDeck/TemplateLoader/TemplateProperty.cs
  VitDeck/Assets/VitDeck/TemplateLoader/Tests/TemplateLoaderTest.cs
  VitDeck/Assets/VitDeck/Templates/Sample_template/Property.asset
  VitDeck/Assets/VitDeck/Templates/Sample_template/SharedAssets/NewSurfaceShader.shader
  VitDeck/Assets/VitDeck/Templates/Sample_template/SharedAssets/NewSurfaceShader.shader.meta
  VitDeck/Assets/VitDeck/Templates/Sample_template/TemplateAssets/{BOOTHID}_{NAME}/Animations.meta
  VitDeck/Assets/VitDeck/Templates/Sample_template/TemplateAssets/{BOOTHID}_{NAME}/Animations/New Animation override.anim
  VitDeck/Assets/VitDeck/Templates/Sample_template/TemplateAssets/{BOOTHID}_{NAME}/Animations/New Animation override.anim.meta
  VitDeck/Assets/VitDeck/Templates/Sample_template/TemplateAssets/{BOOTHID}_{NAME}/Animations/New Animation.anim
  VitDeck/Assets/VitDeck/Templates/Sample_template/TemplateAssets/{BOOTHID}_{NAME}/Animations/New Animation.anim.meta
  VitDeck/Assets/VitDeck/Templates/Sample_template/TemplateAssets/{BOOTHID}_{NAME}/Animations/New Animator Controller.controller
  VitDeck/Assets/VitDeck/Templates/Sample_template/TemplateAssets/{BOOTHID}_{NAME}/Animations/New Animator Controller.controller.meta
  VitDeck/Assets/VitDeck/Templates/Sample_template/TemplateAssets/{BOOTHID}_{NAME}/Animations/New Animator Override Controller.overrideController
  VitDeck/Assets/VitDeck/Templates/Sample_template/TemplateAssets/{BOOTHID}_{NAME}/Animations/New Animator Override Controller.overrideController.meta
  VitDeck/Assets/VitDeck/Templates/Sample_template/TemplateAssets/{BOOTHID}_{NAME}/EmptyFolder.meta
  VitDeck/Assets/VitDeck/Templates/Sample_template/TemplateAssets/{BOOTHID}_{NAME}/EmptyFolder/Dummy.asset
  VitDeck/Assets/VitDeck/Templates/Sample_template/TemplateAssets/{BOOTHID}_{NAME}/EmptyFolder/Dummy.asset.meta
  VitDeck/Assets/VitDeck/Templates/Sample_template/TemplateAssets/{BOOTHID}_{NAME}/Materials/Sample Material.mat
  VitDeck/Assets/VitDeck/Templates/Sample_template/TemplateAssets/{BOOTHID}_{NAME}/Models/Sample_object.fbx.meta
  VitDeck/Assets/VitDeck/Templates/Sample_template/TemplateAssets/{BOOTHID}_{NAME}/Sample_object_prefab.prefab
  VitDeck/Assets/VitDeck/Templates/Sample_template/TemplateAssets/{BOOTHID}_{NAME}/Sample_object_prefab.prefab.meta
  VitDeck/Assets/VitDeck/Templates/Sample_template/TemplateAssets/{BOOTHID}_{NAME}/Scene_{BOOTHID}_{NAME}.unity
Labels: TemplateLoader, enhancement

#43 Feature/#9
  VitDeck/Assets/VitDeck/Main/GUI/InfoWindow.cs
  VitDeck/Assets/VitDeck/Main/PackageDownloader.cs
  VitDeck/Assets/VitDeck/Main/PackageDownloader.cs.meta
  VitDeck/Assets/VitDeck/Main/Repository.cs
  VitDeck/Assets/VitDeck/Main/Repository.cs.meta
  VitDeck/Assets/VitDeck/Main/Tests/RepositoryTest.cs
  VitDeck/Assets/VitDeck/Main/Tests/RepositoryTest.cs.meta
  VitDeck/Assets/VitDeck/Main/Tests/UpdateCheckTest.cs
  VitDeck/Assets/VitDeck/Main/Tests/UpdateCheckTest.cs.meta
  VitDeck/Assets/VitDeck/Main/UpdateCheck.cs
  VitDeck/Assets/VitDeck/Main/UpdateCheck.cs.meta
Labels: Main, enhancement

#47 Feature/#40(Refactoring)
  VitDeck/Assets/VitDeck/AssetGuardian/DelayedDeprotector.cs
  VitDeck/Assets/VitDeck/AssetGuardian/EditorEventHooks.meta
  VitDeck/Assets/VitDeck/AssetGuardian/EditorEventHooks/EditorDelayedAction.cs
  VitDeck/Assets/VitDeck/AssetGuardian/EditorEventHooks/EditorDelayedAction.cs.meta
  VitDeck/Assets/VitDeck/AssetGuardian/EditorEventHooks/UnityAssetDuplicationEvent.cs
  VitDeck/Assets/VitDeck/AssetGuardian/EditorEventHooks/UnityAssetDuplicationEvent.cs.meta
  VitDeck/Assets/VitDeck/AssetGuardian/EditorEventHooks/UnityAssetModificationEvent.cs
  VitDeck/Assets/VitDeck/AssetGuardian/EditorEventHooks/UnityAssetModificationEvent.cs.meta
  VitDeck/Assets/VitDeck/AssetGuardian/EditorEventHooks/UnityAssetPostProcessEvent.cs
  VitDeck/Assets/VitDeck/AssetGuardian/EditorEventHooks/UnityAssetPostProcessEvent.cs.meta
  VitDeck/Assets/VitDeck/AssetGuardian/GUI/Notificator.cs
  VitDeck/Assets/VitDeck/AssetGuardian/Guardian.cs
  VitDeck/Assets/VitDeck/AssetGuardian/Handler.cs
  VitDeck/Assets/VitDeck/AssetGuardian/IAssetProtectionMarker.cs
  VitDeck/Assets/VitDeck/AssetGuardian/IAssetProtectionMarker.cs.meta
  VitDeck/Assets/VitDeck/AssetGuardian/LabelAndHideFlagProtectionMarker.cs
  VitDeck/Assets/VitDeck/AssetGuardian/LabelAndHideFlagProtectionMarker.cs.meta
  VitDeck/Assets/VitDeck/AssetGuardian/LinqExtensions.cs
  VitDeck/Assets/VitDeck/AssetGuardian/LinqExtensions.cs.meta
  VitDeck/Assets/VitDeck/AssetGuardian/ProtectedAssetPostProcessor.cs
  VitDeck/Assets/VitDeck/AssetGuardian/ProtectionLabel.cs
  VitDeck/Assets/VitDeck/AssetGuardian/Protector.cs
  VitDeck/Assets/VitDeck/AssetGuardian/Protector.cs.meta
  VitDeck/Assets/VitDeck/AssetGuardian/Tests/GuardianTest.cs
  VitDeck/Assets/VitDeck/AssetGuardian/Tests/LabelAndHideFlagProtectionMarkerTest.cs
  VitDeck/Assets/VitDeck/AssetGuardian/Tests/LabelAndHideFlagProtectionMarkerTest.cs.meta
  VitDeck/Assets/VitDeck/AssetGuardian/Tests/ProtectionLabelTest.cs
  VitDeck/Assets/VitDeck/AssetGuardian/Tests/TestAssets.cs
  VitDeck/Assets/VitDeck/AssetGuardian/Tests/TestAssets.cs.meta
  VitDeck/Assets/VitDeck/AssetGuardian/Tests/VitDeck.AssetGuardian.Tests.asmdef
Labels: AssetGuardian
